[package]

name = "router"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
license = "MIT"
version = "0.7.0"
description = "A router for the Iron framework."
repository = "https://github.com/iron/router"
documentation = "https://docs.rs/router"
keywords = ["iron", "web", "http", "routing", "router"]

[dependencies]
route-recognizer = "0.2"
iron = { path = "../iron", version = "0.6" }
url = "1.1"
